version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        NODE_IMAGE: ${NODE_IMAGE}
        APP_PORT: ${APP_PORT}
    container_name: ${APP_NAME}-app
    env_file:
      - .env
    ports:
      - 3000:${APP_PORT}
    command: sh -c "npm start"
    volumes:
      - ./:/home/app
      - ./node_modules:/home/app/node_modules
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: ${DB_IMAGE}
    container_name: ${APP_NAME}-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - 5432:${DB_PORT}
    networks:
      - app_network

networks:
  app_network:
    name: app_network
